### PR TITLE
New: Add independant loco brake

### PR DESCRIPTION
**Pull request by leezer3**
## New Features:
* Independant loco (driver car) brake. 
* New control additions to support this: LOCOBRAKE_INCREASE & LOCOBRAKE_DECREASE ==> Propose setting to **'** (Apostrophe) and **;** (Semi-colon) to be one row above the current brake controls.
* Differing loco brake types- https://github.com/leezer3/OpenBVE/pull/241#issuecomment-389999632

## TODO:
* Independent gauge variable for Panel2.cfg; CHECK what is currently read, and consider tweaking, although must note that this should not break backwards compatibility.
* Independant handle variable for Panel2.cfg
* Run lint on new / old code before merge.
* Test that nothing has been broken on older stock, and in odd combinations.

### CODE REVIEW

**Comment by leezer3** [comment]
Some more work / fixing.

This now functions well if our loco brake notch count is identical to that of the plain brake.
Have done some abstracting of the handle classes, but not entirely happy with it.

In an ideal world, all the handles would inherit from a base abstract type (Thus allowing one reference to brake handle as opposed to two for the notched/ non-notched types), but they're all radically different, and hence not easy to add together.
Using an object for the handle declaration might work, but it's crappy unreadable code :(

### Flaws:
* No support for non-notched handles (See complaint above). 
* No support for a per-car deceleration figure. At the minute, it just uses a proportion of the base train's deceleration, wheras (e.g.) a loco working an unfitted freight would provide 95% of the deceleration from the loco itself.

**Comment by leezer3** [comment]
It's amazing the things you find when doing something like this....
https://github.com/leezer3/OpenBVE/commit/166cda205cb0e19f36aa132eebd0186558b8096b

All the framework was in place to use a separate delay per-notch, just needed hooking up.
Would have left it for this PR, but it was a small change, other than the train editor gubbins, and I'm not sure when this one will get finished....

**Comment by leezer3** [comment]
Rebased to be mergable, and added the following types of LocoBrake:

- Combined (Default)- The locomotive's brakes operate at the higher of the train brake and the locomotive brake settings.
- Independant- The locomotives brakes operate independently of the train brakes.
- Blocking- The locomotives brake blocks the train brakes from releasing below it's level.

**Comment by OpenBveTrainSim** [comment]
Leezer:
Referencing "Types Of LocoBrake" being Combined\Independent\Blocking:
considering the Knorr\WABCo Model 26L (dating from 1957 and later)
controls for the Train\Auto and Loco\Inde are somewhat interactive, meaning 
if the Train\Auto brake handle is applied the Loco\Inde brake follows with its own application,
unless the Loco\Inde brake handle is Depressed\Bailed by the driver,
allowing the Loco\Brake handle to be Released\Applied "Independent" of the Train\Auto brake handle.

Tech info for the 1957 model 26L and recent equivalent computerized versions:
http://sdrm.info/faqs/brakes/control/26stand.html
https://www.youtube.com/watch?v=akiS1euJWyg
http://www.nyabproducts.com/ccb-26/
http://nyab.com/media/nyab_1/documents_1/technical/partscatalogpc/PC-780634-C.pdf

The 26L and equivalent modern versions is likely the most common air brake control worldwide.
I'm less familiar with equivalent Faiveley, Oerlikon, Dako, IRAB,... models,
but suspect they also have simular interactive Auto and Inde functions.
I'm thinking a default key to "Depress\Bail" the Loco\Inde handle and brakes may be appropriate.
Thanks
OBTS

**Comment by leezer3** [comment]
UK locomotives are a tad different than US, but somewhat similar.
You normally get two distinctly separate handles rather than a single assembly.
Numbers 1 and 17 here:
http://www.brushtype4fund.co.uk/Class_47_Controls/index.htm

Your exact behaviour depends on the locomotive itself, and the refit status, and broadly follows the three options I've outlined above.

I suppose a bail-off key could be added, but that opens up numerous cans of worms, as to the correct behaviour of things.
As far as I can see though, **combined** mode operates reasonably closely to what you're after, other than the missing bail-off key.

**Comment by OpenBveTrainSim** [comment]
Leezer:
Do you know the name of the component manufacturer or have any tech\model info for the
Train\Auto Brake and Loco\Inde\StraightBrake handles\valves on the Class 47 or other British locos?
A detailed spec sheet for these would likely reveal interesting details.  They look like an Oerlikon FV4 train brake and FD1 loco brake, or equivalent by a UK manufacturer; guessing here?

Before 1957, many UIC, AAR and Australian locomotives, including early diesels, had steam era style Train and Loco brake handles which where physically seperate, but yet still had a "Bail Off" function for the Loco brake via a pneumatic interlock between the 2 valves.  That's why I suspect British and UIC brakes have a simular function.

Thanks
OBTS

**Comment by leezer3** [comment]
For a 47 (and for most UK locos for that matter), they'll be either Westinghouse (air brakes) or Davies & Metcalfe (vaccuum brakes) products. This depends on refit status and build date.

The one in the linked image is a later refit to allow selectable air / vaccuum train brakes; The original had vaccuum only train brakes, and air brakes on the locomotive.

On the 47 linked (this is straight from the original Brush driver's manual, which I have a copy of here), in original unrefitted format:
* Train brake handle: Applies the vaccuum brakes on the train, and the air brakes on the locomotive, using the triple-valve system. (Essentially, the vaccum is converted into the same proportion of air brake application)
* Air brake handle: Applies the air brake on the locomotive only.

In refitted format:
* Train brake handle: Applies EITHER the vaccuum brakes on the train, and the air brakes on the locomotive, using the triple-valve system. (Essentially, the vaccum is converted into the same proportion of air brake application) OR the air brakes on the entire train.
* Air brake handle: Applies the air brake on the locomotive only.

No bail-off of any description, the locomotive brakes simply apply the higher of the two settings.

BR fault finding manual FWIW:
[Westinghouse Dual Brake Equipment Fault Finding- Issue 3.pdf](https://github.com/leezer3/OpenBVE/files/2040934/Westinghouse.Dual.Brake.Equipment.Fault.Finding-.Issue.3.pdf)

Scanned copy of the paper manual for the dual-brake system (Not mine):
http://locodocs.co.uk/brmanuals/DriversBrakingInstructions-33056-3-Issue1.htm

**Comment by OpenBveTrainSim** [comment]
Leezer:
Interesting reading.; vacuum brakes; another can of worms!
Does appear as you've said, no mention of a "Bail Off" on BR brakes.
Old post WW1+WW2 reconstruction era locomotives in Europe had Westinghouse air brakes with a pneumatic Bail Off interlock.   Suspect that function was required by American and Australian drivers to minimize slack in very long trains inherent in those countries, but did not find real need in Europe or Britain and thus disappeared along with steam.

Another item that is not usual on BR locomotives: Dynamic\Resistive\Regen\Electric brakes.
Mackoy's old doumentation make a very brief mention of this function in the train.dat #Brake settings,
Wondering about your considerations for this type of locomotive brake?

Thanks
OBTS

**Comment by OpenBveTrainSim** [comment]
Leezer:
More info on the D&M+Oerlikon Brake Valves.
https://www.worthpoint.com/worthopedia/class-47-davies-metcalfe-brake-manual-163103418
Loco\Straight\Direct\Independent Brake Valve FD1
http://www.stabeg.at/jpg/ventil_fd.jpg
https://image.jimcdn.com/app/cms/image/transf/dimension=origxorig:format=jpg/path/s7e87b8486332f523/image/ic4cba4129cbfb6f6/version/1479121139/image.jpg
http://www.stabeg.at/html_de/ersatzteil.php?Geraet=FD+1
https://www.youtube.com/watch?v=CAJNKRfSpkg
Train\Automatic Brake Valve FV4
http://www.stabeg.at/jpg/ventil_fv4a.jpg

Thanks
OBTS

**Pull request merged**
