### PR TITLE
New: Option to control the other handles when EB is applied in Train.dat

### PR DESCRIPTION
**Pull request by leezer3**
https://github.com/leezer3/OpenBVE/issues/234

This adds an option to control the behaviour of the other handles when EB is applied
Available options:
* NoAction
* PowerToNeutral
* ReverserToNeutral
* PowerReverserToNeutral

Whilst I don't always like altering opaque formats like Train.dat, this is a simple change, and is backwards compatible.
(Prior versions of openBVE will silently ignore this. Unsure what BVE4 will do, but it rejects **OPENBVE** format specified train.dat files anyway)

### Potential changes:
* ~~Do we need a newer format specifier (e.g. **OPENBVE1500** or something)- Doing this, and a comparision of the string against the 'current' format specifier would then allow us to detect the fact that we're using a newer train.dat than supported and prompt to upgrade?~~ DONE.

### CODE REVIEW

**Comment by OpenBveTrainSim** [comment]
Chris:
Recommend a serious detailed study of typical\standard real world train braking systems, 
ie those on actual DMUs, EMUs, Metro, Locomotive stock and Passenger+Goods Wagons,
both historic and modern systems, so they may be more realisticly simulated in OpenBVE.
Likely speaking here of things you already know well.

Most common air brake system manufacturers:
Knorr, WABCo, Oerlikon, Dako, Mitsubishi, IRAB\India, Schaltbau, Secheron, Gessman, Xian\China...
And the legacy vacuum brake system manufacturers:
Gresham & Craven, IRAB\India...

My 2 pence worth.
OBTS

**Comment by leezer3** [comment]
Sure, I'm well aware of most of the IRL systems.
Unfortunately, simulation of most of these isn't something that's likely to come quickly. The WIP XML train format allows control of some of the fixed parameters within the system, but that's not anywhere close to being ready for general public consumption.

This however is a simple change within the existing framework to allow a small piece of logical & requested behaviour :)

**Comment by OpenBveTrainSim** [comment]
Chris:
Umm.  Then OpenBVE train developers desiring to closely simulate real brakes,
have only limited .Animated logic or cumbersome custom .DLL\ATS functions.
Maybe some day.  Thanx
OBTS

**Comment by leezer3** [comment]
Added an openBVE version parameter to the train.dat file.

This will generate a small (harmless) error if used with prior versions of openBVE, which will then silently ignore any extra parameters.

**Comment by cwfitzgerald** [comment]
Before this gets pushed could there be an updated to the docs regarding the new sections? I can do it if need be.

**Comment by leezer3** [comment]
Its documented in the included docs copy, but not the site, which I'll push when this is ready. Don't want to put a draft feature into the public docs :)
Need to add the train.dat versioning too, but thats minir and doesn't really do anything useful ATM.

**Comment by cwfitzgerald** [comment]
Wonderful! Thanks!

Of course :)

**Comment by leezer3** [comment]
Merged and main documentation updated.

Not really a new section as such, just one additional parameter in the **#HANDLE** section, and an (optional) addition to the **OPENBVE** identifier in case something else like this gets added.

**Pull request merged**
