### PR TITLE
Implement locomotive air brakes & improve brakesystem internals

### PR DESCRIPTION
**Pull request by leezer3**
This is a WIP followup to https://github.com/leezer3/OpenBVE/pull/241

Work summary:
- ~~The different brake types must be combined into a single root abstract class, so we can just declare & refer to a abstract handle for any type, and access further down via derived types if necessary. Otherwise, we end up with a stupid mess of different handle types~~ (Complete-ish, requires testing before porting to power handles)
- ~~Air brakes need implenting for the locos.~~
- ~~Loco brake settings added to the API.~~ (Requires testing)
- Really ought to add auto self-lapping brakes as per BR practice. Should be simple enough, all that requires is a percentage of service cylinder pressure.....

Later TODO:
- Need to revisit splitting the brake system bits and bobs & combining things. Way too much accessing of stupidly placed properties.....

### CODE REVIEW

**Comment by leezer3** [comment]
This should be reasonably feature complete, other than the wish for self-lapping percentage based brakes.

Requires testing to ensure that the API and air brakes work correctly before merging.

**Comment by leezer3** [comment]
Completely rehacked the brake system internals, and re-implemented most of changes from here:

https://github.com/leezer3/OpenBVE/pull/158

Rather complicated, but I *think* that having separate loco brake and train brake types might actually work now....

TODO:
* Implement into Train Editor
* Fix loading from train.dat
* TEST

**Comment by leezer3** [comment]
Fixed some more issues and FFWD relative to master.
Still needs considerable checking / testing.

**Comment by leezer3** [comment]
Testing with a couple of hacked around UK outline trains works OK, but still digging.

**Comment by leezer3** [comment]
Massive squelch and fast-forward.

Wait for Travis / AppVeyor to build and then merge:
This appears complete and functional, and now needs to be in the mainline as otherwise we get divergence again....

**Comment by OpenBveTrainSim** [comment]
Chris:
Program build and brake changes of 31July screws up legacy locomotives that were previously able to have both brake and power applied simultaneously and "creep" at Power 1 or 2 from full stop up to a low speed determined by the 3rd value in Train.dat Brake section (dynamic\motor brake minimum speed).  This is useful for adjusting stop position and for maintaining a crawl for "merry go rounds".

Brake notch 1 will bring train to a quick full stop with throttle at full Power; not realistic for traditional locomotive pulled trains.  May be OK for MultipleUnits, but not a traditional locomotive with goods wagons or coaching stock.

Brake system improvements\changes\options likely need more testing before going into final program distribution.
Thanks
OBTS

**Comment by leezer3** [comment]
I will take a look- Any chance of a link to an affected train please?

Trouble is that if these changes don't get into the nightly builds, the testing is limited to essentially me and my collection of stuff.
On the flip side, absolute stability and functionality should only really be expected with a stable numbered build. Nightlies are for finding stuff like this :)

**Comment by leezer3** [comment]
@OpenBveTrainSim 
Have found a potentially related issue, although I still don't have any trains which exhibit the behaviour you describe. Please test the current build:
https://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2018-08-03.zip

**Pull request merged**
