### PR TITLE
Fix: Linux builds not uploading after Mono bump again...

### PR DESCRIPTION
**Pull request by s520**
I'm sorry. There seems to be an error.

### CODE REVIEW

**Comment by leezer3** [comment]
Will do a better fix once I'm home, ought to be ignoring the minor ver & build, else this'll break if they patch it.

**Comment by s520** [comment]
Oops...
Thanks.
This PR will close.

**Comment by leezer3** [comment]
Kicked so that it parses the Mono version into an array and tests the first two entries.
Should now be uploading again.

Re-visiting the build and upload scripts is something that's somewhere at the bottom of my pile of stuff I ought to do.... (Keep thinking about a CAKE build system and a bit more logging)
We could probably dump the SLN building workers too now the makefile builds the SLN.

**Comment by s520** [comment]
Certainly uploaded.
Thanks!
I can now post an introduction to TrainEditor2 on the forum...

**Pull request closed without merging**
