### PR TITLE
Update: version of .NET Framework installed by the Windows installer to 4.6.1

### PR DESCRIPTION
**Pull request by s520**
This PR update version of .NET Framework installed by the Windows installer to 4.6.1.

### CODE REVIEW

**Comment by s520** [comment]
@leezer3 
Is there a problem with this PR?

**Comment by leezer3** [comment]
Sorry no issue as such :)

Did you see my comment / query on the publisher name?

**Comment by s520** [comment]
Well, what does that mean?
Does that mean changing the publisher name?

**Comment by leezer3** [comment]
Correct.

The publisher  name is currently me, and this is definitely not just me :)
The OpenBVE Project is used elsewhere  in the source and is perhaps more appropriate?

**Comment by s520** [comment]
OK.
I fix it.

**Pull request merged**
