### PR TITLE
Fix: Building.md [ci skip]

### PR DESCRIPTION
**Pull request by s520**
The changes are as follows:
- Added description about GNU Make.
- Fixed the command to install NuGet client.

I searched the openSUSE build environment to solve the problem posted on the forum.
Would you like to add a note about openSUSE?

### CODE REVIEW

**Comment by leezer3** [comment]
No idea, never tried openSUSE for anything serious.

If we're not careful though, we'll have a set of instructions for everything under the sun.
My impression from the post in question was of someone rather non-technical. 

Marginally surprised that make isn't a default install on Debian.
Might be better to link to the build-essential metapackage in this case? We don't use the other components of it, but it's a little more well-known, and probably far more useful.

**Comment by s520** [comment]
I agree with your thoughts.
There are descriptions of the major distributions, Debian and RHEL, which should be sufficient.

I changed to use metapackage instead of make.
If there's nothing else to write about, please merge this PR.

**Comment by s520** [comment]
Also, we need to link [the build page](https://openbve-project.net/source/) on the official homepage to this file.

**Comment by leezer3** [comment]
OK, took a little messing around, but the build documentation now mirrors this file.

**Comment by s520** [comment]
I checked it out.
Thanks!

**Pull request merged**
