### PR TITLE
Train refactor

### PR DESCRIPTION
**Pull request by leezer3**
### Nov 17- Updating to note what has been manually done (This PR is completely out of date), will strikeout comments as done

Current changes:
* ~~Separate out most structs into separate files (Will eliminate some later)~~
* ~~Make the axle position a property of the axle itself.~~
* Make exterior loading a property of the train.
* Move car motion into a property of the train. (Possibly ought to be the car itself, but each car is a train!)
* ~~Convert several items to a Vector3 rather than 3 doubles.~~
* ~~Move Horns to be a property of the car~~
* ~~Move point, run and flange sounds to the axle~~
* ~~Check encoding of Extensions.cfg file~~
* ~~Move sounds and properties into the doors~~
* ~~Make disposal a property of the train~~
* ~~Run and motor sound updates removed from the lump and into separate functions~~
* ~~Move car relative camera updates to the car~~
* ~~Physics and speed update methods moved to the train~~

Other notes:
* Some of the logic abstraction work has needed to be done slightly differently. See the BVE5 branch https://github.com/leezer3/OpenBVE/pull/154

### Final Remaining:
Final remaining work to close out the changes in this PR on mainline is to manually merge the BrakeSystems code.
Should be relatively quick to do, and parts of this are required for the BVE5 PR.

Also need to seriously investigate creating a SoundManager root class, but that will probably happen well after the BVE5 initial merge.

### CODE REVIEW

**Comment by leezer3** [comment]
Have just merged the Brake System refactor into this branch manually, as that branch ended up too far behind master....

This separates out the Air Brake into a separate namespace (OpenBve.BrakeSystems) and does some other minor twiddling.

TODO:
* Most of the TrainManager properties aren't really stored in the right places, and should actually be a property of the class themselves.
* Structural changes.

**Comment by leezer3** [comment]
Dunno why Travis threw a wobbly on the last commit, but it appears OK.

**Comment by Sirflankalot** [comment]
Bizzare, it just didn't go for one of the VMs.

**Comment by leezer3** [comment]
Starting to get somewhere here.

Most of the functions that previously lived in TrainManager are now specifically a property of whatever they affect, rather than passing it in as a parameter, which is insane.

__Issues:__
* Still far too many oversized functions.
* A lot of stuff is practically gibberish, no documentation at all....
* Various places where things are incomplete/ marked with TODO (Generally Michelle)
* Most of the moved functions require XML-Doc comments.

__TODO:__
* Test thorougly. (BVE2 / 1 trains?)
* A couple of seriously oversized functions still remain in TrainManager. These are used to update the physics, and probably require splitting into some more sensible parts.
* Split some of the train/ car based stuff into separate files??

**Comment by leezer3** [comment]
Separated some more stuff from the TrainManager, and distilled a few bits into more manageable functions.

I think the devices remaining in CarSpecs should probably be a property of the car itself, but keep the physics based stuff in a holder class.

**Comment by leezer3** [comment]
Rot, makefile not updated.

Will do that tomorrow along with carrying on with this.....

**Comment by leezer3** [comment]
Some further work.

TODO:
* Move the handles from TrainSpecs to a dedicated handles class. (Minor)
* Doors, passengers etc. have previously been split from the TrainManager, but are not properties of the train yet. 

The 'hard' work is now done for most of the rest of this refactor; The train now needs splitting into a partial class, possibly with a single file per set of functions to avoid the massive file bloat issue,
Still need to consider removing the rest of the TrainSpecs class, or possibly renaming once the handles are out (Physical properties? ==> Can we convert to auto properties stuff like mass etc?)

**Comment by leezer3** [comment]
Re-merged the master branch after the XML sound config has been added.

Actually now works after a couple of attempts......

**Comment by leezer3** [comment]
Merge explosion, didn't intend for that to happen, was just trying to get us back to base with master......

**Comment by leezer3** [comment]
So, a PR for a refactor this large tends to get confused when other coding is going on in the background......

Have now started merging the TrainManager refactors manually. (Some slight tweaking to the file structures, but not the code)

**Comment by leezer3** [comment]
Mostly now merged or irrelevant, closing.

**Pull request closed without merging**
