### PR TITLE
Large Decrease in Loading Times

### PR DESCRIPTION
**Pull request by Sirflankalot**
Here're the details of what's in the commits:

- During object optimization during loading, there was a very expensive check of every single check vertex on every other vertex in the object that has very minimal benefit and hurts loading time a lot.
- All polygons that are loaded are turned into triangles because they are vastly more efficient (GPUs can only render triangles, the drivers have to convert every frame anyway)
- Optimization of object optimization routines. 
- Add myself as a developer :)

**Loading:**
Old: 33 sec
New: 15 sec
**Running:**
Old: 60 fps
New: 55 fps

There is a slight loss in runtime performance on my high end system, but on my low end laptop there was a jump from 4 fps to 9 fps. As I start diving into the rendering code and repairing it, this gain will start to get higher and higher. The program is currently heavily CPU limited because of the sheer amount of calls that have to be made to render a frame.

### CODE REVIEW

**Comment by leezer3** [comment]
Would it be better to just disable the duplicate verticies check by default?

Add it as a hidden option in the config file?
There's probably a better way to do it with hash checking mind....

**Comment by Sirflankalot** [comment]
I don't think this check should ever happen within the loading screen of the game. If people design their models even somewhat correctly, this check will do absolutely nothing. In some sort of tooling in the future, sure, but when loading is already so insanely slow, we need to keep it lean. 

Hashing might be able to make the process a little better is we want to implement this in tooling later. The performance decrease was because of the transition to making every face triangles as we have a very high per face cost.

**Comment by leezer3** [comment]
Whilst I agree that under 'normal' circumstances this probably ought to be in tooling, unfortunately, 95% of the objects you'll find in openBVE have been hand-written at this point, and so you'll probably find far more duplicate verticies than you think.

Difficult one though, what it really wants is an optimiser for complete routes (Goes straight back to the static analyser in one of the other issues)

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/pull/126/commits/51cbe3cc6902cfeb091e6e970a91741357249ecb

Unless I'm mistaken, this rather breaks taking a build compiled on one platform to another, which is the point of the function?

I suppose you could replace the Path.Combine with a switch-case statement, but I think that really wants to stay there.

**Comment by Sirflankalot** [comment]
I completely agree. My argument for removing it is that even on some very poorly performing routes, I see no performance loss by not removing duplicates. 

A route optimizer is definitely on the list of tools that I'm going to build down the line. 

As for 51cbe3c, that was my C++ brain taking over and completely forgetting that CLI builds are cross platform. I will roll back that and 12c1e95 because neither of them make any sense. Interestingly enough however, even with the changes a linux built program works perfectly fine on windows. Something must be built into the .NET implementation that accepts both.

**Comment by leezer3** [comment]
Don't quote me on this one, but IIRC using a Linux path separator works OK on Windows, but not in a bunch of cases the other way around...

Sharpcompress definitely doesn't like using the wrong path separator either.

**Comment by Sirflankalot** [comment]
Interesting, I would've thought it was the other way around. Good to know.

**Comment by leezer3** [comment]
Secondary note:
I suspect part of the reason you're seeing no real change on the vertex optimizer, is that practically nobody is throwing around enough polys to significantly impact performance from the optimization process, at least in part because those of us who are doing this understand about optimisation...

I'll try some tests, but I can't guarantee being able to to any real work/ benching until Wednesday, or possibly next week, what with the time of year.

**Comment by Sirflankalot** [comment]
Then what do you think we should do regarding this going forward? I think that for now, especially when models and routes are still made by hand and are low-poly (by modern computing standards), we should forgo vertex optimization in the loading process, and do a complete rewrite of the routine for use in a route optimizer in tooling down the line.

Alright, I don't blame you, it's very busy lately.

**Comment by leezer3** [comment]
No real concern per-se, but I'd much rather not chuck the baby out with the bathwater :)

Other than increasing the loading times, it's not doing any harm, and potentially a little good, hence my inclination to just disable it by default, and add a hidden option. (Frankly, loading times are the least of our worries. I suspect many users would trade off another 10-20s for a little more on the FPS)

Either way though it's probably going to be neglible.

**Comment by Sirflankalot** [comment]
Haha, alright, I'll add a hidden option in the config file. 

I've identified the pain points while running the game and that is definitely my next order of business. 

That's good to hear, same here! :)

**Comment by leezer3** [comment]
Now that's interesting.

Your loading time decrease only seems to work for some stuff.
The NYCTA 1-line loading time drops dramatically. (~15s to ~5s)
Tokiado Shinkansen seems to drop the loading time by ~5s
On the other hand, the loading time for the Plymouth Route actually increases. (~13s to ~22s)

On the Plymouth Route, FPS is approximately the same (Within the margin of error; both builds are floating around 170fps with vsync off)
On Tokiado Shinkansen, FPS has dropped from ~35fps to ~30fps

Any chance of the route you've been using for benching?

My suspicion is that your triangularization is working well for small objects, but is badly hitting the loading of very complex ones, which is only to be expected.
(I've got a **lot** of objects in the ~2,000 vertices range, plus locos which are generally ~6,000-8000 vertices each)

FWIW:
i7 3700
16gb RAM
GTX 670

I'll try a CPU limited laptop tomorrow (1.66ghz Core2Duo) as well as Linux and see what that shows.

**Comment by Sirflankalot** [comment]
That's really bizarre. I'm using the NYCTA-N line with the route (Rush Hour)2.csv. Testing with the R46 8 Car model. Beware, it can be kind of hard to set up because of problems with unlisted dependencies with other model packs. 

I don't think trangularization is to blame, but I won't know until I can hit it with a profiler when I'm home and back on Windows in about 6-7 hours. 

Are you comparing before/after this PR or with or without the secret switch? 

Trangularization is extremely important for any changes I'm going to make in the renderer so that's something I think we have to live with until we can streamline the trangularization process to some time other that optimize time. I think if it would happen when actually parsing the file that would have minimum performance loss but that would require rewriting the parsers which is a longer term project. 

Just so you know, during runtime, we're spending around 35-50% of our time inside the driver (nvoglv32.dll for me), 15% of the time inside RenderFace, and around 15% inside UpdateAnimatedObject. Those will be the things I will be focusing most upon. 

My Desktop Specs (Win):
i7-6700k (4.5 Ghz)
16 Gb RAM
GTX 760 (1.256 Ghz)

My Laptop Specs (Linux):
Celeron 2955U (Haswell Dual Core Celeron) (1.4 Ghz)
4 Gb RAM
Haswell GT-1

**Comment by leezer3** [comment]
Your load areas don't surprise me too much, but it does depend a little bit upon the route as to where the spinning is.

From a brief dig into the N-Line, the only animated objects it's using would appear to be the signals.
The train is rather different, and whilst I haven't got time to bench before going to work, the code used for the animated door sign looks to be something likely to be causing troubles.
(6022.animated, line 107 onwards)

I'd be interested to see what's going on with the train plugin too, will report back when I've done a little benching......


**Other:**
Comparison was done using a build from the current master, and one with the current PR.
Both in debug configuration, but no debugger attached, and logging off in-between test runs.

(The NV driver, or possibly the .Net GC seems to cache some stuff if you simply switch builds)

**Comment by Sirflankalot** [comment]
Yeah, I'll try to bench with a variety of routes to find the pinpoints.

How interesting, let me know your results when you have the time.

I definitely think any comparisons need to be done in release mode as that's what people will be playing. Plus it's unfair to bench CPU operations without optimizations on. 

This may also be due to hard drive caching in main memory by windows. The loading operations appear to be kinda thrashy, so that could be something that helps. 

Do you think we should test after the effects of caching? Because caching is something that will actually help people during real play, we might want to bench after any caching has happened.

**Comment by leezer3** [comment]
OK, so I can approximately reproduce your figures with your given routefile, which is always good.
Load time with a current build from master is ~30s, dropping to ~10s with your modifications.

Whilst I need to go digging into exactly what's happening with a profiler, my first observation is that there are a lot of cylinders in use here, which is going to be killing render performance due to the sheer number of faces. 
4 cylinders * 8 faces * 24 blocks visible on a standard 600m viewing distance- Approximately 1500 vertices to update per-frame just for the fencing.
Add in the 8-face cylinder vertically every meter (Below the conductor rail, I think they're used as a rivet or something?), and it doesn't surprise me that performance is really not good.

If the vertex optimisation was merging all the cylinders (Same material) and attempting to run through the resulting array checking for duplicate verticies, I can absolutely see that being rather slow. (A cylinder by it's very nature will have commonality between at least one point on it's co-ordinates)

**Comment by Sirflankalot** [comment]
**Preface:** All attachments are .csv files with the .txt extension so that they would actually upload as an attachment. 

**Load time:**

So I just profiled on MSVS release mode to see if the object optimization affected the loading process at all. It turns out that the optimization routine basically didn't take any of the time. On all three routes I tested the optimization routine was between 0.7-1.4% of the time, which is really negligible. From the looks of the per function breakdowns there is some work to be done with getting stuff on the GPU but that's something for the future. The attached logs are for the loading process only. 

[Plymoth_FunctionSummary.txt](https://github.com/leezer3/OpenBVE/files/664936/Plymoth_FunctionSummary.txt)
[Q-Train_FunctionSummary.txt](https://github.com/leezer3/OpenBVE/files/664937/Q-Train_FunctionSummary.txt)
[Shinkansen_FunctionSummary.txt](https://github.com/leezer3/OpenBVE/files/664938/Shinkansen_FunctionSummary.txt)

**Run time:**

I actually profiled running on the N line, and these are my results. We sit in `nvoglv32.dll` for 30% of the time, `UpdateAnimatedObject` for 22% of the time, and `RenderFace` for 15% of the time. On the surface this tells me that the renderer needs to be improved as we are paying a massive per-face cost that we really shouldn't be paying. The route I'm using sits at `107450` static triangles on the entire route. With that low of a number, my GPU will be able to render that before it's even had its morning coffee :). 

I'm not sure how much you know about graphics and such so forgive me if this is redundant to you, but looking at a number like 1500 vertices to update seems like nothing at all. If that number was 150,000 I'd start to get a bit worried.

Looking at the line by line breakdown, it's clear to me that the vertex updating is what is causing the issues with `UpdateAnimatedObject`. The problem lies in that we are doing the vertex transformations on the CPU in managed code. If this was an optimized SIMD routine that would be somewhat excusable, but this really needs to be done completely on the GPU. This definitely can be done on the GPU, though a rework of the renderer/object manager is needed as we need to store transformation matrices not just vertices. That's my next project however, so that will be coming within the next couple weeks. 

The issues with `RenderFace` are coming from using immediate mode and setting a whole bunch of state every single face as opposed to only when it needs to change. These are all changes that will all be included in my rework of the renderer. 

This new renderer will be it's own project/.dll so that it can be shared between every project. 

[N-TrainRuntime_FunctionSummary.txt](https://github.com/leezer3/OpenBVE/files/665119/N-TrainRuntime_FunctionSummary.txt)
[N-TrainRuntime_LineSummary.txt](https://github.com/leezer3/OpenBVE/files/665118/N-TrainRuntime_LineSummary.txt)

**Comment by leezer3** [comment]
Absolutely agree with your points about stuffing everything possible onto the GPU.

The cylinders:
I suppose that's 15 years worth of experience with optimizing for the current engine talking. 
It depends somewhat on the route length as to when you start to encounter trouble, but anything above 20,000 faces is asking for trouble. I've found you'll get away with this for short stretches (Laira is about this number), but prolonged distances like this aren't clever.

Immediately in-cab at the start of the N-Line on what I thought was your given routefile (**NYCT - N (SB) [v2.0]\NTT\NYCT- N [Astoria to Bay 50 St] (Rush Hour)2.csv**), I'm seeing the following `23072` static opaque `45` dynamic opaque `333` dynamic alpha.

Somewhat more than you?

Using Paralell.For() or something similar on the two loops may well produce a small gain in the interim, but I don't think it'll be too much unfortunately.
Similarly, I think that the complete update function could well be threaded in the same way, but would need to do some playing to see whether that gets us any more significant speed gains.

Mildly off-topic:
Have you seen this repository
https://github.com/sladen/openbve2/tree/master/OpenBve

This was produced by michelle and abandoned before a lot of stuff was working.

It's using approximately the same approach you're describing (translating etc. the display lists rather than the root verticies) but in a tree-leaf node based structure.

You're heading outside my realms of specific expertise though. I can see the problem clearly enough, but not the solutions in the same way.

**Comment by Sirflankalot** [comment]
Interesting, do you know why you can get away with small sections with a high face count?

Huh, which branch are you using for that? I'm using this PR's branch. The numbers I quoted were from a slightly different routefile, but the number I'm seeing now (with the right routefile) are almost identical to my old ones. It's possible that my new implementation of face melding is doing something different that makes it fold more faces together into a single "face" unit.

It's possible that parallel for will help a bit, I'll play around with it a bit, though we may find that the overhead of multi-threading (which is very high) might cause it to be slower. 

Thanks for the link, I'll look into it to see if there's any insight I can gain from it.

I'll then suggest that we move to a new issue as we've gotten kinda out off topic for this PR. If you have any more changes you need before you pull this, let me know and I'll change them as soon as I can. I'll make an issue in the repo about runtime performance where we can discuss this more. 

I'm working on getting some of the boilerplate down for the new renderer, mostly dealing with shaders and stuff. I haven't yet pushed the branch, I'll let you know when I do so you can monitor progress.

**Comment by leezer3** [comment]
Face counts were with the current master, but thinking about it logically, I suspect that your changes will probably have an effect on what's going on, although my initial instinct would be that they would have increased the face count numbers, not the other way around. (More triangles used to make a shape than a simple poly...)

Face-load wise, I'd strongly suspect that there's a 'limit' after which things get rather slow.
Probably varies a little by machine.

High face counts also tends to lead to high numbers of textures- Last time I ran in GDebugger, the most expensive openGL call by far was binding a new texture.

**Comment by Sirflankalot** [comment]
There is a limit, but the limit is extremely high. The gpu spends most of its time working on shading pixels rather than dealing with vertices. I've rendered scenes with a couple million verts and my gpu was fine. 

Texture switches also need to be reduced so some kind of sorting should be implemented in the renderer.

**Comment by Sirflankalot** [comment]
Hope your holiday season is going well, just checking in with regards to what more needs to be done to this branch before pulling etc. I may have a little time to work soon, so I should know what I have to do.

**Comment by leezer3** [comment]
Should be relatively mergable I think.

Only thing I wonder, is whether in light of your most recent set of benching, it's worth just cherry-picking the triangularization commits and leaving off the optimization stuff?

**Comment by Sirflankalot** [comment]
You mean just pushing the triangulation code and leaving the old optimization code on? If so, I really think there's no downside to pushing the whole thing, as there's minimal loss in frame rate, and a decent increase in fps. With the insane amount of time the optimization function once took with all the old optimization code, I think we really should turn it off. 

If you mean leaving out the triangulation code until later, I'd be alright with that, though we may see a decent decrease in frame rate because of it.

**Comment by leezer3** [comment]
Fair enough, will try and merge shortly.

Separate issue:
The makefile still seems broken somewhere....

- Auto-compiled build works OK on Windows.

- Auto-compiled build generates no errors.

- Autom-compiled build doesn't work under Linux....

**Comment by Sirflankalot** [comment]
Interesting... I'll check on it when I get home. Probably some dependency issue.

**Comment by leezer3** [comment]
Not sure....

FWIW, the error I was sent:
```
user@user-All-Series:~/デスクトップ/Newest OpenBVETEST_it can delete/1227$ mono ./OpenBve.exe

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'OpenBve.Interface' threw an exception. ---> System.MissingMethodException: Method 'Array.Empty' not found.
  --- End of inner exception stack trace ---
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'OpenBve.Interface' threw an exception. ---> System.MissingMethodException: Method 'Array.Empty' not found.
  --- End of inner exception stack trace ---
user@user-All-Series:~/デスクトップ/Newest OpenBVETEST_it can delete/1227$ 
```

Having spun up a 12.04 VM, with the latest Mono project repos the compiled build doesn't work there either, which is a little odd.

3.2.8 isn't in the default Mono project repos (3.10.0 is the earliest they keep), but it builds and runs OK with 3.10.0, so I have some hopes that just bumping the minimum Mono version in Travis might work.

Need to test the build that the 12.04 VM produced on my other boxes before commiting the change....

**Comment by leezer3** [comment]
OK, so it's an issue with the latest version of Mono, which seems to have changed something somewhere.
Updating to the latest from the Xamarin repo fixes the issue.

I've got the Linux based builds working OK by backing the publish Mono version to 3.2.8, now trying to get the OS-X builds to co-operate in this regard too...

**Comment by Sirflankalot** [comment]
What version of mono are you running? I'm running the latest version from within Ubuntu's repos for 16.04.  I'll try to install the Xamarin repo to see if that changes anything.

**Comment by Sirflankalot** [comment]
I just tested it out after upgrading to the Xamarin repositories with the following version and it compiles and runs fine. If you could attach the 14.04 compiled version so I could test it here, that might be helpful if you can't track down the issue.

```
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 21 12:08:40 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

```

**Comment by leezer3** [comment]
The Ubuntu boxes are all running the latest Ubuntu build (mono-complete)
15.04 (Out of support, but barely):
```
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```
14.04 (Current LTS):
```
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

```

12.04 (Current LTS):
```
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```
Haven't got anything later immediately to hand, but builds are broken on all of these.
( http://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2016-12-27.tar.gz )
I'd say something probably changed in the Mono 4.0 series somewhere.

Where two out of the three LTS Ubuntu distros are broken, I think rolling back is worthwhile.
Today's latest build ( http://vps.bvecornwall.co.uk/OpenBVE/Builds/OpenBVE-2016-12-28.tar.gz ) works on all three.

**Comment by leezer3** [comment]
https://github.com/leezer3/OpenBVE/commit/408a63cf8bc50419dfbca295f01a65d5d4385432

Nothing too special, just rolled back the publishing Ubuntu build to use 3.2.8
OS-X has been left on latest, have tried 3.2.8 and 3.10.0 and both don't compile, and it's not worth the debugging effort to try and figure out where the change happened (The app requires a min of 4.2, which seems to work OK)

**Comment by Sirflankalot** [comment]
That's all fine with me, I have no qualms with the changes. If it's all fine with you, I think this is ready to pull. 

FYI: You have the rights to push onto the branch that I'm doing a PR from if you ever want to make a minor change to my PR when I do one.

**Comment by leezer3** [comment]
Noted, although that's probably a way to generate 10 commits a minute...

Also, another O/T note:
The current master (as of this merge) has shifted a whole bunch of common functions into the API, as opposed to in the main program lump.
https://github.com/leezer3/OpenBVE/commit/2cad7ceaea5eaf43262203a6e5f70a61cd75a443
https://github.com/leezer3/OpenBVE/commit/667bfbd21c3c9d8c959b1a014f0a0e192da567db

I'm going to try and finish extracting these parser functions tomorrow and then try and push an updated stable-ish build, along with newer Route Viewer & Object Viewer builds.
My next intended target is then to add reloading the current route to the main program, as the initial starting point for merging Route Viewer into it.
Tracking issue for this created here:
https://github.com/leezer3/OpenBVE/issues/133

**Comment by Sirflankalot** [comment]
Haha, very true.

That's very good news. Question regarding the new renderer as I write it. It's going to be a separate module (BveRenderer.dll) as it will probably end up being quite large. Do you think this should be part of OpenBveApi or should it stay separate? I think it should stay separate so that when we're building something like the train editor, we don't have to pull in all of the code for the renderer. 

As I plan to rewrite the parsers (a decent distance in the future) to a more standard recursive decent style (faster and more resilient) do you think they should have their own project (something like BveParse.dll)? They all need to be in the same module as they will definitely share code, but I have an inclination to keep them separate to avoid the same problem with too much code in the API.

Great to hear there is progress with merging the RouteViewer!

**Comment by leezer3** [comment]
Hmm, as soon as I merge it, I find a bug I hadn't spotted.....

Something a little funky is happening with a few objects.
Object extract ( **Object\plymrb\bridges\stgob.b3d** ):
```
[MeshBuilder]
Vertex -10.7,3,0
Vertex -10.7,3,7
Vertex -10.7,4.5,7
Vertex -10.7,4.5,0
Vertex -10.4,4.9,0
Vertex -10.4,4.9,7
Vertex -9.5,5.45,7
Vertex -9.5,5.45,0
Vertex -7,5.75,0
Vertex -7,5.75,7
Vertex -4,5.75,7
Vertex -4,5.75,0
Vertex 0,5.3,0
Vertex 0,5.3,7
Vertex 2,5.0,7
Vertex 2,5.0,0
Vertex 4,4.3,0
Vertex 4,4.3,7
Vertex 5,3.85,7
Vertex 5,3.85,0
Vertex 6,3.1,0
Vertex 6,3.1,7
Vertex 6.35,2.5,7
Vertex 6.35,2.5,0
Vertex 6.35,-1,0
Vertex 6.35,-1,7
Face 3,2,1,0
Face 2,3,4,5
Face 7,6,5,4
Face 6,7,8,9
Face 11,10,9,8
Face 10,11,12,13
Face 15,14,13,12
Face 14,15,16,17
Face 19,18,17,16
Face 18,19,20,21
Face 23,22,21,20
Face 22,23,24,25
Color 40,40,40

;Shadow
[MeshBuilder]
Vertex -10.7 ,  3.845 ,  0 ,
Vertex -10.7 ,  3.845 ,  7 ,
Vertex -4.2 ,  -0.145 ,  7 ,
Vertex -4.2 ,  -0.145 ,  0 ,
Vertex 6.35 ,  -0.145 ,  0 ,
Vertex 6.35 ,  -0.145 ,  7 ,
Face 0, 1, 2, 3,
Face2 5,4,3,2
Color 0,0,0,170,
```

The shadow on this is flickering to white.
b1

You can see it on the Plymouth route by jumping to St. Germans (Overbridge just past the station)

Moving the camera makes it go back to 'normal' , as does trains moving though it in the sim, which makes me suspect the two face groups have been merged, breaking the depth test?

Re separate projects:
The eventual aim is to have parsers in their own DLL, same as the image/ sound loaders.
I've actually added a relatively complete Loksim3D object loader, and there's a 50% complete BVE5 parser too (Separate branch though), and plenty of people would like to see this loading other simulation stuff.

**Comment by Sirflankalot** [comment]
How bizarre. I can replicate it as well on Plymouth. I see a similar problem happening with the N/Q NYCTA lines as well, shown below. The lamps are supposed to be yellow.

error1
error2

Unless there is some other depth test I don't know about in the code, the only one that is happening is on the graphics card, and that used the triangles actual positions on screen to do the checking. 

My thought is that something along the line expects a triangle type face to only have 3 verts etc. so _that_ code is doing something funky when it finds triangles that have more than one set of triangles in them. I'll test without the combiner code on, and see if that alleviates the problem. While removing that is not a solution, I don't feel inclined to go and try and fix the underlying problem, when I'm rewriting the renderer anyway. 

Re separate projects:
That sounds great. As part of preparation for the writing of the big ol' editor, I definitely want to implement reading of files that can come from other sources, such as .obj etc. I agree that separate .dlls will be good. I defiantly think that my BveCoreUtils is a good place to put something like BveParse.dll and BveRender.dll to keep them organized. I am also putting them in their own namespace so it's easy to import.

**Comment by leezer3** [comment]
Hmm, been doing some debugging this morning on the transparent face issue.

Some notes and a 'solution' in the issue above, but I'm not sure what the root cause is, other than something's not getting reset properly.
Can you drop into it and take a proper prod at what's going on, as you seem to know more about openGL states than me?

If necessary I think the 'solution' should be OK until the new renderer arrives, but I'm not as happy with it as I could be.

**Pull request merged**
