### PR TITLE
Change translation and cleaning

### PR DESCRIPTION
**Pull request by JunmoreHeavyBox**

### CODE REVIEW

**Comment by JunmoreHeavyBox** [comment]
Waiting...

**Comment by JunmoreHeavyBox** [comment]
I noticed that the switch menu doesn't seem to have a translation applied...

**Comment by JunmoreHeavyBox** [comment]
Excuse me @leezer3 I want you to check

**Comment by leezer3** [comment]
Other than the removal I've noted above, this is OK.
Please can you put these back.

These strings are definitely used in the GL main menu on MacOS.

**Comment by JunmoreHeavyBox** [comment]
I don't understand what you mean.
I should have used branches for work.

**Comment by JunmoreHeavyBox** [comment]
Forget it, that's it.
[Changed Language Files.ZIP](https://github.com/leezer3/OpenBVE/files/14358119/Changed.Language.Files.ZIP)

@leezer3 I really want to apply these translation modifications.

**Comment by JunmoreHeavyBox** [comment]
Thank you!

**Comment by JunmoreHeavyBox** [comment]
@leezer3 I think I understand what you mean, and I am about to discuss the issue of redundancy in language items.
I found some unused items and some conflicting items.
[en-Redundancy.xlf.txt](https://github.com/leezer3/OpenBVE/files/14407669/en-Redundancy.xlf.txt)

To solve an interesting problem, I insist on removing conflicting item. If you don't want to delete it, move it below the conflict item.
Also, I don't want to have two "origin".

If I were to directly discuss language redundancy, then this would only be an issue related to contributing to translation, are not a PR...

**Pull request closed without merging**
