### PR TITLE
Fix: issue where panel elements with NighttimeImage defined are rendered with lighting enabled

### PR DESCRIPTION
**Pull request by s520**
In BVE4 and 5, panel elements with NighttimeImage defined are rendered with lighting disabled. (#498)

Currently, it is not possible to specify an emissive color for the panel, so the author cannot substitute this effect.
If we want to address this issue like that of a CSV object, we should add an emissive color setting.
However, this effect is the same from BVE4, so I don't think it needs to be changed.

### CODE REVIEW

**Comment by leezer3** [comment]
I agree it doesn't need changing for a 2D cab.

Something else I've thought of as a result of this:
A panel.cfg cab (BVE2) should possibly be rendered with lighting disabled too. Before alternate night-time images were possible, it was common for there to be two versions of any given train in a day / night variation, & the **Track.Brightness** command didn't exist & so the whole thing remained at a constant brightness.
Doing this would make the lighting / overall effect 'original' but on the flip side, I'm not sure that it's necessary and in most cases the revised effect looks decent. 
It only really has a major effect if you try to use a BVE2 nightime cab on a route which uses brightness commands. Could add a hack to control this?

Any thoughts on that one?

**Comment by s520** [comment]
I don't think the program can tell if the cab selected by the user is a nighttime cab.
So why not have the user input whether it's a nighttime cab or not when the user selects a train?
This checkbox is clickable only when panel.cfg cab is selected.
The state of this checkbox toggles whether lighting is enabled when drawing the cab.

**Comment by leezer3** [comment]
Correct, not easily autodetectable. (Although for English content could key off night in the folder name & a panel.cfg)

I was thinking more of a hardcoded list, either by adding it to a new database, or by hardcoding them in the parser.
The issue with problem with adding a checkbox is getting it found by the average user

**Comment by s520** [comment]
If full automatic detection is difficult, we should leave the user with a choice.
As an aid, the program will guess from the folder name and change the default state of the checkbox.
Or, as you say, it will check against the database and change the default state.

If the program assists to some extent, the average user should be fine with the defaults.

**Pull request merged**
