### PR TITLE
New: Allow user selectable font

### PR DESCRIPTION
**Pull request by leezer3**
This PR allows a user selectable font for the main menu and the in-game UI.
Only tested on Windows at the minute, and may end up being restricted to this- Most likely to be an issue is going to be the font selector combox.

Depending on the exact font, rendering glitches can also be seen at the top / bottom of the text in-game occasionally, even in Windows (this is a known issue with the default font on some Linux installs)
Probably when the font glyph is colored in the top pixel row, and it might be worth investigating the glyph set for a glitching font.

font

#789

### CODE REVIEW

**Comment by ginga81** [comment]
I would be very grateful if we could be change not only the font type but also the size.
left unders informations are a bit small for me.

**Comment by leezer3** [comment]
Try the HUD size slider, set to large.

This really ought to be renamed, as it actually controls the font size for most things in-game, as well as the OSD.
Will need to take a look into the code to see how well resizing the doors indicator etc. would work dynamically, as that might be a problem.

Could just rename this to font size, and add a few more graduations to it I suppose.....

**Comment by ginga81** [comment]
Oh!
Thank you very much!
I'm sorry to bother your time.

**Comment by leezer3** [comment]
Done a lot of messing with the font drawing routines today.

This PR now fixes the font bleeding under Mono (e.g. https://github.com/leezer3/OpenBVE/issues/772 )
We still have trouble with characters with massive tails on some fonts, but it's much better.

### TODO:
* Font needs to be regenerated in librender2 when changed from the main menu (takes effect after game restart otherwise)
* Mac font is currently hardcoded (due to Unicode glyph set)- Needs to be changed.
* Why do most fonts under Mono / Linux show up as un-renderable? Can we hide these [bunch of squares looks horrid]?

**Comment by leezer3** [comment]
Bit more work to block the non-renderable fonts from being displayed in our font picker- Turns out these are mostly the uncommon Noto variants which use the Western character set to provide more codepoints.....

Need to block anything non-usable on Apple, which I haven't yet tested.

Could possibly actually merge the two (soon to be three) lists.

@danfe
Merging this PR will add the Noto CJK fonts as a soft dependancy, which I'll need to check with regards to FreeBSD to see about the correct font naming. 
Most GUI Linux desktop systems will have these installed already (Chrome / KDE commonly pull them in), but I don't know exactly how common they're likely to be on FreeBSD.
At ~30mb, I'd be inclined to add them as a requirement in your port, but YMMV :)

**Comment by danfe** [comment]
> Merging this PR will add the Noto CJK fonts as a soft dependency, which I'll need to check with regards to FreeBSD to see about the correct font naming. [...] I don't know exactly how common they're likely to be on FreeBSD.

We do have Noto fonts in the ports collection (so the port can depend on them), but CJK are further split into _-hk_ (Traditional Chinese Hong Kong), _-jp_ (Japanese), _-kr_ (Korean), _-sc_ (Simplified Chinese), _-tc_ (Traditional Chinese) packages, probably owing to their size (these fonts are quite beefy).

Overall this looks like a useful feature.  I'll be interested to see if it can remedy the blurriness I've mentioned in the end of issue #712.

**Comment by leezer3** [comment]
Beefy is somewhat of an understatement looking at the port :/
https://www.freshports.org/x11-fonts/noto
~1gb download.

Debian on the other hand is 75mb download, and appears to be in just about any desktop package.
https://packages.debian.org/stretch/fonts-noto-cjk

Much less happy about adding a 1gb dependancy than a 75mb one which is in most places by default, I think you'll have to be the best judge here as to whether it's worth doing this.
FWIW, looking at the latest Cloudflare stats, I'd guess probably 60% + of our userbase is from Korea / Japan / HK, which makes getting proper unicode showing for most of these in the main menu by default is actually a massive deal :)

---

Bluryness:
I can't see much difference TBQH. Cleartype under WinForms is a mess under Windows, let alone anywhere else (heavily dependant on DPI, screen resolution and all sorts of other mess)

Might be better, but it's somewhat hard to tell anything useful after completely changing the font- I haven't patched anything else in this regard.

---

Other Linux / BSD related patches in there whilst I was at it:
* FreeBSD now shows the nag prompt if running as **root** / **sudo** (absolutely no need for this under any circumstances)
* Changed the bug report window to use an internal popup to show logs under Linux / BSD as opposed to a shell launch. (otherwise does nothing unless we've got a default .txt handler, as opposed to under Windows showing the choose app prompt)
* Using the close button on the main form was unreliable, and often crashed under BSD. This appears to be a Mono bug in that the filesystem watcher doesn't like being disposed as things are closing.

**Comment by danfe** [comment]
> Beefy is somewhat of an understatement looking at the port :/ https://www.freshports.org/x11-fonts/noto ~1gb download.

This is a meta-port which includes _all_ fonts by depending on the corresponding basic, emoji, extra, and CJK ports.  It's intended for user convenience (manual installation) and not to be used as a dependency.

> Debian on the other hand is 75mb download, and appears to be in just about any desktop package. https://packages.debian.org/stretch/fonts-noto-cjk

Right.  As I've said, FreeBSD splits it even further (one CJK into sC, tC, H, J, and K).

> Much less happy about adding a 1gb dependency than a 75mb one which is in most places by default, I think you'll have to be the best judge here as to whether it's worth doing this.

Of course no need to depend on that huge meta-package, just on `x11-fonts/noto-jp` and/or other `x11-fonts/noto-??` should be sufficient.

**Comment by leezer3** [comment]
The three fonts we're specifically setting based upon locale at the minute are as follows:
```
Noto Sans CJK JP
Noto Sans CJK KR
Noto Display
```

I believe this would be:
```
x11-fonts/noto-basic
x11-fonts/noto-jp
x11-fonts/noto-kr
```

Noto Display has the Cyrillic character set, the JP version has JP & some CN / common (I believe enough to be OK for our usage), and KR does Hangul.
@Kenny-Hui or another native Chinese speaker using Linux is going to be better placed to comment as to whether it wants the specific SC variant though. As someone with a basic / translator grasp of Chinese, all I can really do is check for missing glyphs and that it is the same as Windows.

**Comment by danfe** [comment]
> Noto Display
> I believe this would be `x11-fonts/noto-basic`

Hmm, per what I see, `noto-basic` includes just the standard Sans and Serif families, Display comes from the `noto-extra` package (please confirm or deny).

**Comment by Kenny-Hui** [comment]
> @Kenny-Hui or another native Chinese speaker using Linux is going to be better placed to comment as to whether it wants the specific SC variant though. As someone with a basic / translator grasp of Chinese, all I can really do is check for missing glyphs and that it is the same as Windows.

From my limited testing, they all seems to render fine without the SC variants. (Well, at least before my installation got screwed up)
Though most of the content I have is all Traditional Chinese, not too sure about simplified

**Comment by leezer3** [comment]
> > Noto Display
> > I believe this would be `x11-fonts/noto-basic`
> 
> Hmm, per what I see, `noto-basic` includes just the standard Sans and Serif families, Display comes from the `noto-extra` package (please confirm or deny).

You're right :/
Comes from the core package in Debian, but plain Noto Sans seems to be OK, so switching to that instead.


> > @Kenny-Hui or another native Chinese speaker using Linux is going to be better placed to comment as to whether it wants the specific SC variant though. As someone with a basic / translator grasp of Chinese, all I can really do is check for missing glyphs and that it is the same as Windows.
> 
> From my limited testing, they all seems to render fine without the SC variants. (Well, at least before my installation got screwed up) Though most of the content I have is all Traditional Chinese, not too sure about simplified

Thanks :)

**Comment by leezer3** [comment]
Now merged.

I'm going to leave this a week or so in the hope that any new glitches in the daily builds get picked up by someone (really.....) but will put out a release after this, as IMHO it's a pretty significant step for new users.

----

### KNOWN ISSUES:
* Some fonts with massive tails (couple of handwriting style ones on my Windows box) may lose the end of the tail in-game- **WONTFIX**
* With some fonts on non-windows platforms, some textboxes in the main form may slightly overlap the borders. I think this is likely a Mono issue- Could possibly increase the spacing in these places slightly to compensate, but not sure it's the best idea, so leaving this alone for the minue.
* There's no single font covering all Unicode codepoints under Linux, and as a result, we need to detect the system locale and pick the most logical one by default. Should be OK, but might need a few more adding- see how we go for the minute.

----

### Other thoughts:
We could possibly use the locale detection code to try and set the native language by default, now we have a good font.
Not sure whether this would be a good idea, and some of our non-english users will need to comment on this- I'm concerned about mis-detections, and what happens in a missing font scenario.
At least, english is relatively widely known?

**Pull request merged**
