### PR TITLE
Fix: a crash in the motor sound simulation

### PR DESCRIPTION
**Pull request by s520**
This PR fix a crash in the motor sound simulation.

However, the numerical value of the scale of the Motor sound settings graph is no longer displayed.

This is because I decided to use OpenGL.

Can I use the main program or viewer text display mechanism?

I am worried about this.

What do you think?

Related to #388 .

### CODE REVIEW

**Comment by leezer3** [comment]
I don't see any reason why the text rendering function couldn't be lifted relatively easily, all it probably wants is the shared renderer importing and the appropriate functions calling.
openGL is openGL at the end of the day.

Having said that, I'm not totally sold on the GLControl idea, as this adds another bunch of overheads, but sooner or later it comes down to what's easiest to maintain.

**Comment by s520** [comment]
Thank you.
Let's incorporate it immediately.
In fact, I didn't realize that I used LibRender until a while ago.

**Comment by s520** [comment]
Now you are ready to merge.
Please check.

**Comment by leezer3** [comment]
I'll merge and do some testing later this week :)

**Pull request merged**
