### PR TITLE
Some cleaning and organising and Chinese language pack

### PR DESCRIPTION
**Pull request by JunmoreHeavyBox**
Finishing work for #860 
- Need to check

#

Update Chinese Language
[Indev Chinese Simplified.zip](https://github.com/leezer3/OpenBVE/files/13481748/Indev.Chinese.Simplified.zip)
- Need to review content

### CODE REVIEW

**Comment by JunmoreHeavyBox** [comment]
Urge, I want to audit.

**Comment by leezer3** [comment]
Should be in the build from today- Thanks!

**Comment by JunmoreHeavyBox** [comment]
Found some omissions.

Missed the end tag
https://github.com/leezer3/OpenBVE/blob/26c7b31de5a9956d82b279fb36b6f25e83edf116/assets/Languages/en-US.xlf#L4047

It should be "Centre point"?
https://github.com/leezer3/OpenBVE/blob/26c7b31de5a9956d82b279fb36b6f25e83edf116/assets/Languages/en-US.xlf#L4093

Missing the middle
("panel_settings", "touch", "sound_command")
https://github.com/leezer3/OpenBVE/blob/26c7b31de5a9956d82b279fb36b6f25e83edf116/source/TrainEditor2/Views/FormTouch.cs#L271-L276
("import_export", "train"
, "any_format")
https://github.com/leezer3/OpenBVE/blob/26c7b31de5a9956d82b279fb36b6f25e83edf116/source/TrainEditor2/Views/FormExport.cs#L238

#

By the way the language files carried in this issue are under review?

**Comment by leezer3** [comment]
Technically, neither is probably completely correct for the second- Probably just origin, but I wouldn't worry about that. 

All the others should be OK now.

**Comment by JunmoreHeavyBox** [comment]
Ugh, Please go see the latest commits in my branch, I don't want comment more...

**Comment by leezer3** [comment]
You're right, duplicate...
That's minor though.

A suggestion for you:
If you add a breakpoint here
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBveApi/Interface/Translations/InterfaceStrings.cs#L122
then you'll hit this every time you get a missing string.

**Comment by leezer3** [comment]
Removed the duplicate string, and have sorted out the issues from the save dialog and the fact that the language wasn't being remembered between runs.

**Comment by JunmoreHeavyBox** [comment]
After this job this thing is over.
Go through the entries in the en language file critically, clean up the deprecated entries and organise them to correspond to the translated code being applied.
Work slowly, I expect you to be well rested.

**Pull request merged**
