### PR TITLE
Change: Attempt to solve memory leak with VAOs

### PR DESCRIPTION
**Pull request by leezer3**
This implements IDisposable on various classes, and changes a lot of the cleanup code in order to try and solve https://github.com/leezer3/OpenBVE/issues/507

### CODE REVIEW

**Comment by leezer3** [comment]
The GC.Collect are probably un-necessary.

### Other things to do:
This also needs to be added to route viewer.
Main program needs considerable testing, this has only really been tested in Object Viewer. Need to check that this won't make things crash (e.g. when jumping around etc)

**Comment by leezer3** [comment]
This now appears stable-
Reload a file in Object Viewer or Route Viewer, and anfter a few minutes the memory usage will settle back to what it was originally.

One thing I'm not so happy about is that this entire implementation specifically relies on the fact that when something is removed from a List<T> the Dispose() method is not called.
If this changed unexpectedly (I haven't gone looking into the C# roadmap), then things would fall over badly.

cc @s520 @ginga81

**Comment by s520** [comment]
The current implementation implements IDisposable but not the finalizer.
So I think we need to call Dispose somehow after it is removed from the list.

I thought of writing a finalizer according to [the C# guide](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose).
This is because the handle obtained from OpenTK is an unmanaged resource.

However, when I tried to delete the handle in the finalizer, I got an AccessViolationException.
So this idea may be wrong in the first place...

**Comment by leezer3** [comment]
Things are a little complicated....
Now that we're using a single prototype instance with multiple references, this makes the standard dispose / finalize pattern a little complicated (As **Dispose()** can be called multiple times, and takes no account of multiple instances of the reference, and we have no explicit control over where finalize is called & thus GL contexts)
The code I've implimented in this PR uses the standard dispose pattern, but relies on the fact that when we remove something from a **List<T> ** the dispose method is not actually called- https://stackoverflow.com/questions/16181693/removeatx-does-it-dispose-the-element-x
Instead, I've added the DisposeAndClear() extension method, which itinerates down the entire chain of references, disposing *everything* as it goes.

To my mind, this is a little dangerous (and only works on a reload) as it fundamentally assumes that there's no further use for anything. and instead aims to clear all used memory.

**Comment by shooking** [comment]
Hi. Your code is open source right? So some commercial static analysis
firms let you run their tools. If you like I can try to run some free ones?
I do it for my day job and it can find some obscure leaks / potential race .
conditions.

**Comment by leezer3** [comment]
Correct, we're open source, although the licence issue is a little complicated due to previous baggage:
https://github.com/leezer3/OpenBVE/issues/305

Any contributions are welcomed :)

The biggest leak itself (well techinically the visible sympton) is relatively obvious: 
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBveApi/Objects/Mesh.cs#L19
As far as I can see from digging with DotMemory and the VS2010 memory viewer (and I'm no professional) a reference to something is being held somehow by the following list after we issue the Clear() command, which in turn prevents the memory from being cleared:
https://github.com/leezer3/OpenBVE/blob/master/source/LibRender2/Objects/ObjectLibrary.cs#L23
The changes in this PR add an explicit dispose method to all components of the class-chain called by an extension method, which seems to work around the problem, but as noted above I don't like this approach.

**Comment by LabRatAndy** [comment]
Could I offer a suggestion. 

All VAOs appear to be added to the static list list disposeable, by the constructor. 
[https://github.com/leezer3/OpenBVE/blob/18a7f1e7ca54be63c3e807fe65f4bc686c37fbd4/source/LibRender2/openGL/VertexArrayObject.cs#L19](url)
[https://github.com/leezer3/OpenBVE/blob/18a7f1e7ca54be63c3e807fe65f4bc686c37fbd4/source/LibRender2/openGL/VertexArrayObject.cs#L36](url)
However, the dipose method doesn't remove the VAO from this list  and so there would still be a reference to the VAO held in this list even though the underlying openGL resources have been cleaned up by the Dipose method. The GC would still think that this dispoesed VAO is still being used due to it being held in the static disposable list and therefore not collect it when it next runs.

**Comment by leezer3** [comment]
All suggestions greatly appreciated 👍 

Will take a closer look tomorrow at where you're linking to (doesn't work at all on the phone :/ )

**Comment by leezer3** [comment]
Good call.

That list gets used here when the renderer cleans up on close:
https://github.com/leezer3/OpenBVE/blob/master/source/LibRender2/BaseRenderer.cs#L260

Looks like we need to clear it at the same time as a reload. Also going to need to clear the FBO list.

NB:
Before the changes in this PR, the **Dispose()** method for the VAO wasn't getting called at all.
Might be better moving it into a destructor.

**Comment by leezer3** [comment]
So, removing those lists helps with *some* of the problem-
This allows the GC to reclaim the system memory.
What it doesn't do however is free the GPU memory.
https://github.com/leezer3/OpenBVE/pull/508#issuecomment-674188776
I also tried deleting the resources in the finalizer, which as noted above crashes with an access violation exception. I think this is likely being caused by a lack of GL context in the finalizer thread- Will experiment a little.

**Comment by leezer3** [comment]
Much better.

I *think* the other PR now solves this properly by using the destructor and an enqueued list on each render pass, can anyone else please take a look and confirm before I merge?

**Pull request closed without merging**
