### PR TITLE
Plugins: Extend door button interface

### PR DESCRIPTION
**Pull request by leezer3**
This allows plugins to detect when the door button has been pressed, regardless of what the doors then do.

### CODE REVIEW

**Comment by leezer3** [comment]
Small TODO:
http://openbve-project.net/documentation/HTML/train_panel2_cfg.html#subjects

The available subjects for doors are as follows:
door
doorl
door
doorl**n**
doorr**n**

What this needs is the ability to show the button press as well as this status, eg.
doorbuttonl
doorbuttonr

Other interesting ideas (Probably requires #158 merging first & XML configuration files):
* Delay before the door opening process begins.
* Control over door opening times. At the minute, this is controlled by the length of the door sound: https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/OldCode/Loading.cs#L235
* Standardize door locking beacons?

**Comment by MarcRiera** [comment]
Thanks for this addition, it will be very useful to improve cab animations.

The other ideas sound great too, especially the latter two. The current sound-based door opening/closing timing is rather cumbersome and precise configuration is practically impossible. Enabling some minor configuration shouldn't make things too complicated, it's one of those things that people don't like because they have a fixed behaviour.

As for the door locking beacons, it is probably a good idea too. I have been using a custom system for a route under development and it would be interesting if the indexes were standardized in order to avoid plugin conflicts. Real-life train safety devices are usually not compatible between each other, but in OpenBVE many people love to ride routes with their favourite trains, so interoperability to some extent would surely be attractive.

**Comment by leezer3** [comment]
First a note:
When I say 'standardizing beacons' , I'm thinking along the lines of a set of dedicated routefile commands, so to take the door interlock as an example:
.DoorInterlock 0;1

e.g. Door interlocking starts from this point, on side 1 (right)

I'm well aware that in 'real' life things very rarely work together (Or for that matter in several cases fit at all), but as you note in a simulation context, allowing things of this nature to work wherever is I think good practice.


The other ideas are in the pipeline, but will take a little longer. Dunno how long, but I need to finish the train refactoring first; At the minute, too many things are stuck in the middle of '00 line functions to give the level of control I'd like.

**Comment by leezer3** [comment]
This tests OK locally and would appear to be ready to merge when Travis has built.

Note: Minor behaviour change, in that the door state no longer bounces when the key is held down, but this seems completely logical to me.

**Pull request merged**
