### PR TITLE
Fix: Issue where the language setting shifted in some languages

### PR DESCRIPTION
**Pull request by s520**
This PR fix issue where the language setting shifted in some languages.

### CODE REVIEW

**Comment by leezer3** [comment]
Can you describe exactly what's going on for this one?
It shouldn't affect anything that I can think of.

I actually added the InvariantCulture check today, as I noticed that the comparison would be broken in a system using a RTL language (e.g. Arabic or Hebrew) as the system language, no matter what the UI language was set to.

**Comment by s520** [comment]
Setting the language setting to Japanese will result in code = ko-KR instead of code = ja-JP at options.cfg.
So I think this issue is caused by [Change: Minor tweaks to API code](https://github.com/leezer3/OpenBVE/commit/a8c82439dc344730590bc2b5dc9758765d91e640).

**Comment by leezer3** [comment]
I can't think how this change would cause that-

All it does is specify that the string should be compared R==>L case insensitively, using the period as the decimal separator & a couple of other mimor options.
Let me try and reproduce this on a Japanese Linux box before we do anything else;.

**Comment by leezer3** [comment]
Hmm.
I can't immediately reproduce anything on Windows or a Ubuntu 15.04 box.

I'm still digging, but I can't find anything that looks like it could cause that....

**Comment by s520** [comment]
Thank you for investigating.
I thought that this problem was caused by the disagreement of the order of "LanguageNames" and "AvailableLangauges".
So I unified the sorting rule into InvariantCultureIgnoreCase.

**Comment by s520** [comment]
I tried that branch and confirmed that this problem has been fixed.
Thanks!

**Comment by leezer3** [comment]
No problem.

I'm doing some further work in that branch restructuring things to generally make that section a little cleaner, but will try and get that merged in tomorrow or Monday.

**Comment by leezer3** [comment]
Should now have be in the current mainline, with https://github.com/leezer3/OpenBVE/commit/33a9452d966935e76bc6c97a7b40bb8fba51444a

This also does a little trickery to load an embedded copy of the en-US language file from within the API if no language files are found.
(N.B. I briefly considered embedding all the language files, but this hides them from being easily user editable)

**Pull request closed without merging**
